## Chapter 1: Getting Started & Inspection

- `.head()`, `.tail()`
- `.shape`, `.size`, `.ndim`
- `.dtypes`, `.info()`, `.describe()`
- `.columns`, `.index`, `.values`
- `.sample()`

In [1]:
pip install scikit-learn kaggle openml tensorflow-datasets tensorflow

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting kaggle
  Downloading kaggle-2.0.0-py3-none-any.whl.metadata (15 kB)
Collecting openml
  Downloading openml-0.15.1-py3-none-any.whl.metadata (10 kB)
Collecting tensorflow-datasets
  Downloading tensorflow_datasets-4.9.9-py3-none-any.whl.metadata (11 kB)
Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (4.4 kB)
Requirement already satisfied: numpy>=1.24.1 in ./miniconda3/lib/python3.13/site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: bleach in ./miniconda3/lib/python3.13/site-packages (from kaggle) (6.3.0)
Collecting kagglesdk<1.0,>=0.1.15 (from kaggle)
  Downloading kagglesdk-0.1.16-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in ./miniconda3/lib/python3.13/site-packages (from kaggle) (25.0)
Collecting protobuf (from kaggle)
  Downloading protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Requirement already satisfied: python-dateutil in ./miniconda3/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Collecting python-slugify (from kaggle)
  Using cached python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: requests in ./miniconda3/lib/python3.13/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in ./miniconda3/lib/python3.13/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in ./miniconda3/lib/python3.13/site-packages (from kaggle) (2.6.1)
Collecting liac-arff>=2.4.0 (from openml)
  Downloading liac-arff-2.5.0.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting xmltodict (from openml)
  Downloading xmltodict-1.0.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: pandas>=1.0.0 in ./miniconda3/lib/python3.13/site-packages (from openml) (3.0.2)
Collecting minio (from openml)
  Downloading minio-7.2.20-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pyarrow in ./miniconda3/lib/python3.13/site-packages (from openml) (23.0.1)
Collecting absl-py (from tensorflow-datasets)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting dm-tree (from tensorflow-datasets)
  Downloading dm_tree-0.1.10-cp313-cp313-macosx_10_13_universal2.whl.metadata (2.6 kB)
Collecting etils>=1.9.1 (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets)
  Downloading etils-1.14.0-py3-none-any.whl.metadata (6.5 kB)
Collecting immutabledict (from tensorflow-datasets)
  Downloading immutabledict-4.3.1-py3-none-any.whl.metadata (3.5 kB)
Collecting promise (from tensorflow-datasets)
  Downloading promise-2.3.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: psutil in ./miniconda3/lib/python3.13/site-packages (from tensorflow-datasets) (7.0.0)
Collecting simple_parsing (from tensorflow-datasets)
  Downloading simple_parsing-0.1.8-py3-none-any.whl.metadata (8.1 kB)
Collecting tensorflow-metadata (from tensorflow-datasets)
  Downloading tensorflow_metadata-1.17.3-py3-none-any.whl.metadata (2.5 kB)
Collecting termcolor (from tensorflow-datasets)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting toml (from tensorflow-datasets)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Collecting wrapt (from tensorflow-datasets)
  Downloading wrapt-2.1.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-1-py2.py3-none-macosx_11_0_arm64.whl.metadata (5.2 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: setuptools in ./miniconda3/lib/python3.13/site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in ./miniconda3/lib/python3.13/site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: typing_extensions>=3.6.6 in ./miniconda3/lib/python3.13/site-packages (from tensorflow) (4.15.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.80.0-cp313-cp313-macosx_11_0_universal2.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.14.0-py3-none-any.whl.metadata (6.3 kB)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-macosx_10_13_universal2.whl.metadata (8.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in ./miniconda3/lib/python3.13/site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/lib/python3.13/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/lib/python3.13/site-packages (from requests->kaggle) (2026.1.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in ./miniconda3/lib/python3.13/site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Collecting einops (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets)
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: fsspec in ./miniconda3/lib/python3.13/site-packages (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets) (2026.2.0)
Collecting zipp (from etils[edc,enp,epath,epy,etree]>=1.9.1; python_version >= "3.11"->tensorflow-datasets)
  Downloading zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: rich in ./miniconda3/lib/python3.13/site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (34 kB)
Requirement already satisfied: webencodings in ./miniconda3/lib/python3.13/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: attrs>=18.2.0 in ./miniconda3/lib/python3.13/site-packages (from dm-tree->tensorflow-datasets) (26.1.0)
Requirement already satisfied: argon2-cffi in ./miniconda3/lib/python3.13/site-packages (from minio->openml) (25.1.0)
Collecting pycryptodome (from minio->openml)
  Downloading pycryptodome-3.23.0-cp37-abi3-macosx_10_9_universal2.whl.metadata (3.4 kB)
Requirement already satisfied: argon2-cffi-bindings in ./miniconda3/lib/python3.13/site-packages (from argon2-cffi->minio->openml) (25.1.0)
Requirement already satisfied: cffi>=1.0.1 in ./miniconda3/lib/python3.13/site-packages (from argon2-cffi-bindings->argon2-cffi->minio->openml) (2.0.0)
Requirement already satisfied: pycparser in ./miniconda3/lib/python3.13/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio->openml) (2.23)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Using cached text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./miniconda3/lib/python3.13/site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./miniconda3/lib/python3.13/site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in ./miniconda3/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Collecting docstring-parser~=0.15 (from simple_parsing->tensorflow-datasets)
  Downloading docstring_parser-0.17.0-py3-none-any.whl.metadata (3.5 kB)
Collecting googleapis-common-protos<2,>=1.56.4 (from tensorflow-metadata->tensorflow-datasets)
  Downloading googleapis_common_protos-1.74.0-py3-none-any.whl.metadata (9.2 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-macosx_12_0_arm64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 19.8 MB/s  0:00:00a 0:00:01m eta 0:00:01
Downloading kaggle-2.0.0-py3-none-any.whl (75 kB)
Downloading kagglesdk-0.1.16-py3-none-any.whl (160 kB)
Downloading openml-0.15.1-py3-none-any.whl (160 kB)
Downloading tensorflow_datasets-4.9.9-py3-none-any.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 21.3 MB/s  0:00:00 21.4 MB/s eta 0:00:01
Downloading tensorflow-2.21.0-cp313-cp313-macosx_12_0_arm64.whl (223.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.8/223.8 MB 5.5 MB/s  0:00:36 eta 0:00:01[36m0:00:02
Downloading grpcio-1.80.0-cp313-cp313-macosx_11_0_universal2.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 5.6 MB/s  0:00:02m 5.6 MB/s eta 0:00:01
Downloading h5py-3.14.0-cp313-cp313-macosx_11_0_arm64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 7.9 MB/s  0:00:00m 7.9 MB/s eta 0:00:01
Downloading ml_dtypes-0.5.4-cp313-cp313-macosx_10_13_universal2.whl (676 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.9/676.9 kB 10.2 MB/s  0:00:00
Downloading protobuf-7.34.1-cp310-abi3-macosx_10_9_universal2.whl (429 kB)
Downloading absl_py-2.4.0-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading etils-1.14.0-py3-none-any.whl (172 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading keras-3.14.0-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.8 MB/s  0:00:00m 4.3 MB/s eta 0:00:01
Downloading libclang-18.1.1-1-py2.py3-none-macosx_11_0_arm64.whl (25.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 6.5 MB/s  0:00:046.4 MB/s eta 0:00:01:01
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading scipy-1.17.1-cp313-cp313-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 8.1 MB/s  0:00:02 eta 0:00:01[36m0:00:01
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading wrapt-2.1.2-cp313-cp313-macosx_11_0_arm64.whl (61 kB)
Downloading dm_tree-0.1.10-cp313-cp313-macosx_10_13_universal2.whl (316 kB)
Downloading einops-0.8.2-py3-none-any.whl (65 kB)
Downloading immutabledict-4.3.1-py3-none-any.whl (5.0 kB)
Downloading minio-7.2.20-py3-none-any.whl (93 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.0-cp313-cp313-macosx_11_0_arm64.whl (392 kB)
Downloading pycryptodome-3.23.0-cp37-abi3-macosx_10_9_universal2.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 3.3 MB/s  0:00:00m 3.8 MB/s eta 0:00:01
Using cached python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading simple_parsing-0.1.8-py3-none-any.whl (113 kB)
Downloading docstring_parser-0.17.0-py3-none-any.whl (36 kB)
Downloading tensorflow_metadata-1.17.3-py3-none-any.whl (31 kB)
Downloading googleapis_common_protos-1.74.0-py3-none-any.whl (300 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading xmltodict-1.0.4-py3-none-any.whl (13 kB)
Downloading zipp-3.23.0-py3-none-any.whl (10 kB)
Building wheels for collected packages: liac-arff, promise
  Building wheel for liac-arff (pyproject.toml) ... done
  Created wheel for liac-arff: filename=liac_arff-2.5.0-py3-none-any.whl size=11769 sha256=e8322143b6e43ebee94e9737f4e9d2fa78d857da4d40aad302cdd043fab5b06c
  Stored in directory: /Users/sakethsreeram/Library/Caches/pip/wheels/93/f3/5b/658a9bddee916a5f4b84bdc1a4e0fabd22fb17947c2c9542e6
  Building wheel for promise (pyproject.toml) ... done
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21581 sha256=781827a7ce50bd4a638a7d525f7428b4ca4c9cd7fe2fefe667d5ec33fee39a52
  Stored in directory: /Users/sakethsreeram/Library/Caches/pip/wheels/8f/46/1c/1f4e5d73a20eb816ead5014e97cdeb3928cf314fc46c7bab61
Successfully built liac-arff promise
Installing collected packages: text-unidecode, namex, libclang, flatbuffers, zipp, xmltodict, wrapt, toml, threadpoolctl, termcolor, scipy, python-slugify, pycryptodome, protobuf, promise, optree, opt_einsum, ml_dtypes, liac-arff, joblib, immutabledict, h5py, grpcio, google_pasta, gast, etils, einops, docstring-parser, astunparse, absl-py, simple_parsing, scikit-learn, kagglesdk, googleapis-common-protos, dm-tree, tensorflow-metadata, keras, kaggle, tensorflow, minio, openml, tensorflow-datasets
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42/42 [tensorflow-datasets]rflow-datasets]]flow]it-learn]
Successfully installed absl-py-2.4.0 astunparse-1.6.3 dm-tree-0.1.10 docstring-parser-0.17.0 einops-0.8.2 etils-1.14.0 flatbuffers-25.12.19 gast-0.7.0 google_pasta-0.2.0 googleapis-common-protos-1.74.0 grpcio-1.80.0 h5py-3.14.0 immutabledict-4.3.1 joblib-1.5.3 kaggle-2.0.0 kagglesdk-0.1.16 keras-3.14.0 liac-arff-2.5.0 libclang-18.1.1 minio-7.2.20 ml_dtypes-0.5.4 namex-0.1.0 openml-0.15.1 opt_einsum-3.4.0 optree-0.19.0 promise-2.3 protobuf-7.34.1 pycryptodome-3.23.0 python-slugify-8.0.4 scikit-learn-1.8.0 scipy-1.17.1 simple_parsing-0.1.8 tensorflow-2.21.0 tensorflow-datasets-4.9.9 tensorflow-metadata-1.17.3 termcolor-3.3.0 text-unidecode-1.3 threadpoolctl-3.6.0 toml-0.10.2 wrapt-2.1.2 xmltodict-1.0.4 zipp-3.23.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
from datasets import load_dataset

# Imdb dataset
dataset = load_dataset('imdb')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [3]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [4]:
df = dataset["train"].to_pandas()

In [5]:
df.head()

                                                text  label
0  I rented I AM CURIOUS-YELLOW from my video sto...      0
1  "I Am Curious: Yellow" is a risible and preten...      0
2  If only to avoid making this type of film in t...      0
3  This film was probably inspired by Godard's Ma...      0
4  Oh, brother...after hearing about this ridicul...      0

In [6]:
print(dataset['train'][0])

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0}

In [8]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [13]:
print("Shape: ", df.shape)
print("Size: ", df.size)
print("Dimension: ", df.ndim)

Shape:  (891, 12)
Size:  10692
Dimension:  2

In [12]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200